[package]
name = "portal-pc-waffle-tunnel"
version = "0.2.4"
edition = "2021"
description = "Simplification for waffle"
license = "CC0-1.0"

[dependencies]
anyhow = "1.0.94"
arena-traits = "0.2.1"
portal-pc-waffle.workspace = true
stacker = "0.1.17"
