[package]
name = "portal-pc-waffle-robake"
version = "0.2.0"
edition = "2021"
description = "Simplification for waffle"
license = "CC0-1.0"

[dependencies]
anyhow = "1.0.94"
arena-traits = "0.2.1"
itertools = "0.14.0"
once_map = "0.4.21"
portal-pc-waffle.workspace = true
waffle-ast = "0.4.3"
